stereo_odometry_node:
  ros__parameters:
    approx_sync: false
    use_sim_time: true
    ground_truth_frame_id: 'odom'
    ground_truth_base_frame_id: 'base_link_gt'
    initial_pose: "0, 0, 0, 0, 0, 0"
